name: Semgrep SAST Scan

on:
  push:
    branches: [ "master", "main" ]

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        run: semgrep scan --config auto
        